language:
   - objective-c
   - python

osx_image: xcode8.2 

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew outdated python || brew upgrade python
  
script:
  - cd "Scripts Pack - create-dmg"
  - ls -l
  - chmod +x "BuildScriptsPackImage.sh"
  - chmod +x "create-dmg"
  - chmod u+x "support/dmg-license.py"
  - "./BuildScriptsPackImage.sh"