language:
   - objective-c
   - python
   - bash

osx_image: xcode8.2 

before_script:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew outdated python || brew upgrade python
script:
  - cd "Scripts Pack - create-dmg"
  - ls -l
  - chmod +x "BuildScriptsPackImage.sh"
  - chmod +x "create-dmg"
  - chmod u+x "support/dmg-license.py"
  - echo "Starting Build Scripts Pack Image Script..."
  - "./BuildScriptsPackImage.sh"
  
deploy:
  overwrite: true
  provider: releases
  api_key: ${GH_TOKEN}
  file: "../Builds/Scripts Pack.dmg"
  skip_cleanup: true
  on:
    repo: Phorofor/ScriptsPack.macOS
    tags: false
    all_branches: true
    
branches:
  except:
    - /^*-v[0-9]/