language:
   - objective-c
   - python
   - bash

osx_image: xcode8.2 

before_script:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew outdated python || brew upgrade python
script:
  - cd "Scripts Pack - create-dmg"
  - ls -l
  - chmod +x "BuildScriptsPackImage.sh"
  - chmod +x "create-dmg"
  - chmod u+x "support/dmg-license.py"
  - echo "Starting Build Scripts Pack Image Script..."
  - "./BuildScriptsPackImage.sh"
  
deploy:
  #tag_name: "Current"
  #prerelease: true
  #draft: false
  #name: "Scripts Pack Current Source Release"
  #target_commitish: now
  #body: "This is where the latest build of the Scripts Pack will be placed which is based upon the latest commit for the Scripts Pack project, expect a lot more errors and mistakes than usual. Still testing things out at the moment."
  #overwrite: true
  provider: releases
  api_key: ${GH_TOKEN}
  file: "../Builds/Scripts Pack.dmg"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true