language:
   - python
   - bash

osx_image: xcode8.2 

before_script:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew outdated python || brew upgrade python
script:
  - chmod +x MAKE
  - ./MAKE
  - cd Builds
  
deploy:
  overwrite: true
  provider: releases
  api_key: ${GH_TOKEN}
  file: "ScriptsPack.dmg"
  skip_cleanup: true
  on:
    repo: Phorofor/ScriptsPack.macOS
    tags: true
    all_branches: true
    
branches:
  except:
    - /^*-v[0-9]/