language:
   - objective-c
   - python

osx_image: xcode8.2 

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew outdated python || brew upgrade python
  
script:
  - cd $HOME
  - cd ScriptsPack.macOS
  - chmod +x "Scripts Pack - create-dmg/BuildScriptsPackImage.sh"
  - chmod +x "Scripts Pack - create-dmg/create-dmg"
  - chmod u+x "Scripts Pack - create-dmg/support/dmg-license.py"
  - "Scripts Pack - create-dmg/BuildScriptsPackImage.sh"